name: Build PWA to APK
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java (prevents JDK prompt)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Initialize project (non-interactive)
        run: |
          bubblewrap init \
            --manifest=https://raghav00p.github.io/manifest.json \
            --skipValidation \
            --nonInteractive \
            --directory=. \
            --manifestUrl=https://raghav00p.github.io/manifest.json

      - name: Build APK (no prompt)
        run: bubblewrap build --no-prompt

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: built-apk
          path: ./output/
