name: Build PWA to APK
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: /usr/lib/jvm/temurin-17-jdk-amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Create config file
        run: |
          mkdir -p twa
          cat <<'EOF' > twa/twa-manifest.json
          {
            "packageId": "com.example.pwa",
            "host": "raghav00p.github.io",
            "name": "My PWA",
            "launcherName": "MyPWA",
            "display": "standalone",
            "themeColor": "#000000",
            "backgroundColor": "#ffffff",
            "startUrl": "/",
            "iconUrl": "https://raghav00p.github.io/icons/icon-192.png",
            "navigationColor": "#000000",
            "navigationColorDark": "#000000",
            "navigationDividerColor": "#000000",
            "navigationDividerColorDark": "#000000",
            "orientation": "portrait",
            "fullScopeUrl": "https://raghav00p.github.io/",
            "maskableIconUrl": "https://raghav00p.github.io/icons/icon-512.png",
            "enableNotifications": false
          }
          EOF

      - name: Initialize and build (non-interactive)
        run: |
          cd twa
          bubblewrap init --manifest=twa-manifest.json --skipValidation --nonInteractive --directory=. --jdkPath=$JAVA_HOME
          bubblewrap build --jdkPath=$JAVA_HOME --no-prompt

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-apk
          path: twa/output/
